### ISSUE TITLE
Allow a Predis RedisClient

### ISSUE THREAD

**Issue by clementtalleu** [clementtalleu/php-redis-om#73]
Purpose an alternative to the phpredis extension by develop another client using Predis

**Comment by flug** [comment]
Pr proposal https://github.com/clementtalleu/php-redis-om/pull/75

**Comment by flug** [comment]
I'm noticing that there's quite a strong coupling with the redisclient in your code in various places. I'll have to decouple that.

**Comment by flug** [comment]
I'm just having trouble with the executeraw for the search methods, for example, which are not working properly.

**Comment by flug** [comment]
I found it and I'll give you the PR in a while.

**Comment by clementtalleu** [comment]
Nice ! thank you 🫶
