### ISSUE TITLE
How to configure a spéecifiqueredis / predis client connexion in the GenerateSchema  ?

### ISSUE THREAD

**Issue by azurams** [clementtalleu/php-redis-om#86]
In `Talleu\RedisOm\Command\GenerateSchema::generateSchema()` RedisObjectManager is instanciated with default PredisClient / Redisclient . 

How can we configure a specific host / port / database ?

**Comment by clementtalleu** [comment]
Dis you try to add theses env var ?

`
REDIS_CLIENT=phpredis
REDIS_HOST=<your host>
`

In the GenerateSchema :

```
$redisOm = new RedisObjectManager(
            getenv('REDIS_CLIENT') === 'predis' ? new PredisClient() : new RedisClient(),
        );
```
        
Then in the RedisClient / PredisClient

`public function __construct(protected ?\Redis $redis = null)
    {
        $this->redis = $redis ?? new \Redis(array_key_exists('REDIS_HOST', $_SERVER) ? ['host' => $_SERVER['REDIS_HOST']] : null);
    }`    
    
    
I think host/port and database must be set directly as environment variables.

I'll take care of it quickly

**Comment by azurams** [comment]
no i did't, i'll give it a try, 
But i wonder if redis / predis connection could be injected in RedisObjectMapper with DI / psr11 Container Interface anywhere it could be needed ?

**Comment by clementtalleu** [comment]
You can add some env var now to use specific host/port

https://github.com/clementtalleu/php-redis-om/pull/87

**Comment by clementtalleu** [comment]
should update to 0.2.6
