### ISSUE TITLE
Benchmarks in the blog post should be clear about what they are comparing

### ISSUE THREAD

**Issue by stof** [clementtalleu/php-redis-om#90]
Benchmarks in https://les-tilleuls.coop/blog/php-redis-om-un-object-mapper-pour-redis#performances have results for `* Redis` and `* Doctrine`.
I assume that the Redis results are the results for this redis-om package. However, there is no explanation about what `Doctrine` refers to. Is it the Doctrine ORM or the Doctrine MongoDB ODM (or another exotic implementation of `doctrine/persistence`) ? "Doctrine" is not the name of a project but of an organization maintaining *multiple* persistence-related projects for PHP.
And if using the ORM, it would make sense to specify which database platform was used (results might vary a lot, especially for such simple benchmark when sqlite might shine thanks to removing the network latency). And also clarifying whether your `find*By` tests are querying an indexed field or a non-indexed field.

And finally, it would probably be a good idea to have redis-om using JSON and redis-om using HASH on the same chart instead of using separate charts, as that would also allow comparing them.

**Comment by clementtalleu** [comment]
Yes, I should have said more about the test conditions, I did it a bit quickly and it lacks detail.
It was the doctrine bundle, in a Symfony project with a frankenphp docker image.
I'd have to redo this benchmark, specifying everything and testing on indexed or non-indexed properties, and with or without the cache.
In the meantime, I'm going to modify the article to add more details about the technologies involved.

**Comment by clementtalleu** [comment]
Yes, because I'm still on holiday, so I'll do it when I get back.
